set nocompatible
set secure
set nomodeline
set noswapfile
set nobackup
set nowritebackup
set encoding=utf-8
set number
set expandtab
set shiftwidth=2
set softtabstop=2
set tabstop=2
set mouse=a
set shell=/bin/false
cabbrev q! q!
