import { ArrowLeft, ArrowRight, Menu, ShoppingBag, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { api } from "../lib/api";
import type { AppSpec, PreviewView, ProductItem, SourceFile } from "../types";

const networkGuard = `(() => {
  const blocked = (value) => {
    try {
      const raw = typeof value === 'string' ? value : value && value.url;
      const host = new URL(raw, window.location.href).hostname.toLowerCase();
      return host === 'localhost' || host.endsWith('.localhost') ||
        /^127(?:\\.[0-9]{1,3}){0,3}$/.test(host) ||
        host === '[::1]' || host === '::1' || host === '0.0.0.0';
    } catch (_) {
      return false;
    }
  };
  const deny = (value) => {
    if (blocked(value)) throw new TypeError('Localhost and loopback network access is blocked');
  };
  const nativeFetch = window.fetch.bind(window);
  window.fetch = (input, init) => {
    try { deny(input); } catch (error) { return Promise.reject(error); }
    return nativeFetch(input, init);
  };
  const nativeOpen = XMLHttpRequest.prototype.open;
  XMLHttpRequest.prototype.open = function(method, url, ...rest) {
    deny(url);
    return nativeOpen.call(this, method, url, ...rest);
  };
  const NativeWebSocket = window.WebSocket;
  window.WebSocket = class extends NativeWebSocket {
    constructor(url, protocols) {
      deny(url);
      super(url, protocols);
    }
  };
})();`;

interface PreviewAppProps {
  spec: AppSpec;
}

export function PreviewApp({ spec }: PreviewAppProps) {
  const [route, setRoute] = useState<"home" | "catalog" | "product">("home");
  const [selected, setSelected] = useState<ProductItem | undefined>(spec.products[0]);
  const [menuOpen, setMenuOpen] = useState(false);

  if (spec.html) {
    return <CodePreview spec={spec} />;
  }

  if (spec.products.length === 0) {
    return (
      <div className="generated-loading">
        <strong>{spec.project_name}</strong>
        <span>This preview has no catalog products to display yet.</span>
      </div>
    );
  }

  const go = (next: "home" | "catalog" | "product", product?: ProductItem) => {
    if (product) setSelected(product);
    setRoute(next);
    setMenuOpen(false);
    window.scrollTo({ top: 0, behavior: "smooth" });
  };

  return (
    <div
      className="generated-app"
      style={
        {
          "--app-primary": spec.primary_color,
          "--app-accent": spec.accent_color,
          "--app-bg": spec.background_color,
        } as React.CSSProperties
      }
    >
      <header className="generated-nav">
        <button className="wordmark" onClick={() => go("home")}>{spec.project_name}</button>
        <nav className={menuOpen ? "generated-links open" : "generated-links"}>
          <button className={route === "home" ? "active" : ""} onClick={() => go("home")}>Home</button>
          <button className={route === "catalog" ? "active" : ""} onClick={() => go("catalog")}>Catalog</button>
          <button className="bag-button" aria-label="Shopping bag" title="Shopping bag">
            <ShoppingBag size={18} /> <span>0</span>
          </button>
        </nav>
        <button
          className="generated-menu"
          onClick={() => setMenuOpen((value) => !value)}
          aria-label="Toggle navigation"
          title="Toggle navigation"
        >
          {menuOpen ? <X /> : <Menu />}
        </button>
      </header>

      {route === "home" && <Home spec={spec} go={go} />}
      {route === "catalog" && <Catalog spec={spec} go={go} />}
      {route === "product" && <ProductDetail product={selected ?? spec.products[0]} go={go} />}

      <footer className="generated-footer">
        <strong>{spec.project_name}</strong>
        <span>{spec.tagline}</span>
        <span>Preview generated by Another Atom</span>
      </footer>
    </div>
  );
}

function CodePreview({ spec }: { spec: AppSpec }) {
  const javascript = spec.javascript.replace(/<\/script/gi, "<\\/script");
  const css = spec.css.replace(/<\/style/gi, "<\\/style");
  const html = spec.html.replace(/<script[\s\S]*?<\/script\s*>/gi, "");
  const srcDoc = `<!doctype html>
<html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; img-src data: blob:; connect-src http: https: ws: wss:; font-src 'none'; media-src data: blob:; form-action 'none'; base-uri 'none'">
<style>${css}</style></head><body>${html}<script>${networkGuard}</script><script>${javascript}</script></body></html>`;
  return <iframe className="generated-code-preview" sandbox="allow-scripts" srcDoc={srcDoc} title={spec.project_name} />;
}

function localPath(value: string): string | null {
  const trimmed = value.trim();
  if (!trimmed || trimmed.startsWith("#") || /^[a-z][a-z0-9+.-]*:/i.test(trimmed) || trimmed.startsWith("//")) return null;
  const normalized = trimmed.split(/[?#]/, 1)[0].replace(/^\.\//, "");
  return normalized && !normalized.startsWith("/") && !normalized.split("/").includes("..") ? normalized : null;
}

function assetDataUrl(file: SourceFile): string | null {
  if (file.path.endsWith(".svg")) return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(file.content)}`;
  return null;
}

function buildDocumentPreview(files: SourceFile[]): string {
  const byPath = new Map(files.map((file) => [file.path, file]));
  const index = byPath.get("index.html");
  if (!index) throw new Error("Runtime-bound Preview is missing index.html");
  const documentNode = new DOMParser().parseFromString(index.content, "text/html");
  documentNode.querySelectorAll('meta[http-equiv="Content-Security-Policy" i]').forEach((node) => node.remove());
  documentNode.querySelectorAll('link[rel="stylesheet"][href]').forEach((node) => {
    const path = localPath(node.getAttribute("href") ?? "");
    const file = path ? byPath.get(path) : undefined;
    if (!file) return;
    const style = documentNode.createElement("style");
    style.textContent = file.content;
    node.replaceWith(style);
  });
  documentNode.querySelectorAll("script[src]").forEach((node) => {
    const path = localPath(node.getAttribute("src") ?? "");
    const file = path ? byPath.get(path) : undefined;
    if (!file) return;
    const script = node.cloneNode(false) as HTMLScriptElement;
    script.removeAttribute("src");
    script.removeAttribute("integrity");
    script.textContent = file.content.replace(/<\/script/gi, "<\\/script");
    node.replaceWith(script);
  });
  documentNode.querySelectorAll("img[src]").forEach((node) => {
    const path = localPath(node.getAttribute("src") ?? "");
    const file = path ? byPath.get(path) : undefined;
    const dataUrl = file ? assetDataUrl(file) : null;
    if (dataUrl) node.setAttribute("src", dataUrl);
  });
  const policy = documentNode.createElement("meta");
  policy.setAttribute("http-equiv", "Content-Security-Policy");
  policy.setAttribute("content", "default-src 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; img-src data: blob: https:; connect-src https: wss:; media-src data: blob: https:; font-src data:; form-action 'none'; base-uri 'none'");
  documentNode.head.prepend(policy);
  const guard = documentNode.createElement("script");
  guard.textContent = networkGuard;
  documentNode.body.prepend(guard);
  return `<!doctype html>\n${documentNode.documentElement.outerHTML}`;
}

function DocumentCodePreview({ preview }: { preview: PreviewView }) {
  const prepared = useMemo(() => {
    try {
      return { srcDoc: buildDocumentPreview(preview.source_bundle?.files ?? []), error: "" };
    } catch (reason) {
      return {
        srcDoc: "",
        error: reason instanceof Error ? reason.message : "Preview source could not be prepared",
      };
    }
  }, [preview.source_bundle]);
  if (prepared.error) return <div className="generated-loading"><strong>Preview unavailable</strong><span>{prepared.error}</span></div>;
  return <iframe className="generated-code-preview" sandbox="allow-scripts" srcDoc={prepared.srcDoc} title={preview.app_spec.project_name} />;
}

function Home({
  spec,
  go,
}: {
  spec: AppSpec;
  go: (route: "home" | "catalog" | "product", product?: ProductItem) => void;
}) {
  return (
    <main>
      <section className="generated-hero">
        <div className="generated-hero-copy">
          <p className="generated-eyebrow">Curated essentials · Edition 01</p>
          <h1>{spec.hero_title}</h1>
          <p>{spec.hero_body}</p>
          <button className="generated-cta" onClick={() => go("catalog")}>
            Explore collection <ArrowRight size={17} />
          </button>
        </div>
        <button className="generated-hero-image" onClick={() => go("product", spec.products[0])}>
          <img src={spec.products[0].image_url} alt={spec.products[0].name} />
          <span>{spec.products[0].name} · {spec.products[0].price}</span>
        </button>
      </section>
      <section className="generated-featured">
        <div className="generated-section-head">
          <div><span>01</span><h2>Selected objects</h2></div>
          <button onClick={() => go("catalog")}>View all <ArrowRight size={16} /></button>
        </div>
        <ProductGrid products={spec.products.slice(0, 3)} go={go} />
      </section>
      <section className="generated-statement">
        <span>Our principle</span>
        <p>Fewer objects, better considered. We select for utility, material honesty, and a long useful life.</p>
      </section>
    </main>
  );
}

function Catalog({
  spec,
  go,
}: {
  spec: AppSpec;
  go: (route: "home" | "catalog" | "product", product?: ProductItem) => void;
}) {
  const categories = useMemo(
    () => ["All", ...new Set(spec.products.map((product) => product.category))],
    [spec.products],
  );
  const [category, setCategory] = useState("All");
  const products = category === "All" ? spec.products : spec.products.filter((p) => p.category === category);
  return (
    <main className="generated-catalog">
      <div className="generated-page-title">
        <p className="generated-eyebrow">The complete collection</p>
        <h1>Objects for considered spaces.</h1>
      </div>
      <div className="generated-filters" aria-label="Product categories">
        {categories.map((item) => (
          <button className={item === category ? "active" : ""} onClick={() => setCategory(item)} key={item}>
            {item}
          </button>
        ))}
      </div>
      <ProductGrid products={products} go={go} />
    </main>
  );
}

function ProductGrid({
  products,
  go,
}: {
  products: ProductItem[];
  go: (route: "home" | "catalog" | "product", product?: ProductItem) => void;
}) {
  return (
    <div className="generated-grid">
      {products.map((product, index) => (
        <button className="generated-product" key={product.id} onClick={() => go("product", product)}>
          <div className="generated-product-image">
            <img src={product.image_url} alt={product.name} />
            <span>{String(index + 1).padStart(2, "0")}</span>
          </div>
          <div><span>{product.category}</span><strong>{product.name}</strong><em>{product.price}</em></div>
        </button>
      ))}
    </div>
  );
}

function ProductDetail({
  product,
  go,
}: {
  product: ProductItem;
  go: (route: "home" | "catalog" | "product", product?: ProductItem) => void;
}) {
  return (
    <main className="generated-detail">
      <button className="generated-back" onClick={() => go("catalog")}>
        <ArrowLeft size={17} /> Back to catalog
      </button>
      <div className="generated-detail-layout">
        <div className="generated-detail-image"><img src={product.image_url} alt={product.name} /></div>
        <div className="generated-detail-copy">
          <p className="generated-eyebrow">{product.category}</p>
          <h1>{product.name}</h1>
          <div className="generated-price">{product.price}</div>
          <p>{product.description}</p>
          <dl><div><dt>Material</dt><dd>Selected, durable finish</dd></div><div><dt>Dispatch</dt><dd>2–4 business days</dd></div></dl>
          <button className="generated-cta">Add to selection <ShoppingBag size={17} /></button>
        </div>
      </div>
    </main>
  );
}

export function PreviewLoader({ kind, id }: { kind: "preview" | "public"; id: string }) {
  const [preview, setPreview] = useState<PreviewView | null>(null);
  const [error, setError] = useState("");
  useEffect(() => {
    const load = kind === "preview" ? api.preview(id) : api.publicApp(id);
    load.then(setPreview).catch((reason: Error) => setError(reason.message));
  }, [id, kind]);
  if (error) return <div className="generated-loading"><strong>Preview unavailable</strong><span>{error}</span></div>;
  if (!preview) return <div className="generated-loading"><span>Loading preview…</span></div>;
  if (preview.source_bundle?.runtime_binding?.contract_id === "web-static-document") {
    return <DocumentCodePreview preview={preview} />;
  }
  return <PreviewApp spec={preview.app_spec} />;
}
